rtx.enableFirstBounceLobeProbabilityDithering = False
rtx.dlfg.enable = False
rtx.neuralRadianceCache.trainingMaxPathBounces = 6
rtx.di.spatialSamples = 2
rtx.neuralRadianceCache.qualityPreset = 0
rtx.minOpaqueSpecularLobeSamplingProbability = 0.05
rtx.di.enableRayTracedBiasCorrection = False
rtx.demodulate.enableDirectLightBoilingFilter = False
rtx.graphicsPreset = 2
rtx.dlssPreset = 0
rtx.restirGI.biasCorrectionMode = 1
rtx.qualityDLSS = 4
rtx.russianRouletteMaxContinueProbability = 0.7
rtx.neuralRadianceCache.smallestResolvableFeatureSizeMeters = 0.06
rtx.neuralRadianceCache.targetNumTrainingIterations = 2
rtx.russianRoulette1stBounceMinContinueProbability = 0.4
rtx.di.stealBoundaryPixelSamplesWhenOutsideOfScreen = False
rtx.rayreconstruction.model = 0
rtx.enableUnorderedResolveInIndirectRays = False
rtx.di.initialSampleCount = 3
rtx.integrateIndirectMode = 2
rtx.pathMaxBounces = 2
rtx.enableTransmissionApproximationInIndirectRays = True
rtx.neuralRadianceCache.terminationHeuristicThreshold = 0.001
rtx.postFilterThreshold = 10
rtx.volumetrics.froxelDepthSlices = 48
rtx.enableUnorderedEmissiveParticlesInIndirectRays = False
rtx.neeCache.enable = True
rtx.renderPassIntegrateDirectRaytraceMode = 0
rtx.denoiseDirectAndIndirectLightingSeparately = False
rtx.minOpaqueDiffuseLobeSamplingProbability = 0.05
rtx.renderPassIntegrateIndirectRaytraceMode = 2
rtx.volumetrics.froxelGridResolutionScale = 32
rtx.gui.showLegacyTextureGui = False
rtx.di.enableDenoiserConfidence = False
rtx.di.disocclusionSamples = 2
rtx.di.permutationSamplingNthFrame = 1
rtx.di.enableBestLightSampling = False
rtx.gui.textureGridThumbnailScale = 0.75
rtx.pathMinBounces = 0
rtx.restirGI.useReflectionReprojection = False
rtx.reflexMode = 1
rtx.postfx.enable = False
rtx.russianRouletteMode = 1
rtx.upscalerType = 1
rtx.usePostFilter = False
rtx.di.enableSampleStealing = False
rtx.neeCache.enableModeAfterFirstBounce = 2
rtx.enableStochasticAlphaBlend = False
rtx.renderPassGBufferRaytraceMode = 0
